export const products = [
  {
    id: 1,
    title: "Chocolate",
    price: 33,
    count: 50,
    imgUrl: "chocolate.jpg",
    imgAlt: "chocolate",
  },
  {
    id: 2,
    title: "Chips",
    price: 54,
    count: 12,
    imgUrl: "chips.jpg",
    imgAlt: "chips",
  },
  {
    id: 3,
    title: "Energy Drink",
    price: 46,
    count: 15,
    imgUrl: "energy_drink.jpg",
    imgAlt: "energy_drink",
  },
  {
    id: 4,
    title: "Bubble Gym",
    price: 31,
    count: 27,
    imgUrl: "bubble_gym.jpg",
    imgAlt: "bubble_gym",
  },
  {
    id: 5,
    title: "Skittles",
    price: 27,
    count: 13,
    imgUrl: "skittles.jpg",
    imgAlt: "skittles",
  },
  {
    id: 6,
    title: "Soda",
    price: 35,
    count: 26,
    imgUrl: "soda.jpg",
    imgAlt: "soda",
  },
  {
    id: 7,
    title: "Water",
    price: 30,
    count: 36,
    imgUrl: "water.jpg",
    imgAlt: "water",
  },
  {
    id: 8,
    title: "Lollipop",
    price: 18,
    count: 55,
    imgUrl: "lollipop.jpg",
    imgAlt: "lollipop",
  },
];
